apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: forms-assistant
data:
  NODE_ENV: 'production'
  PORT: '4000'
  JWT_ACCESS_TTL: '15m'
  JWT_REFRESH_TTL: '30d'
  CORS_ORIGIN: 'https://app.alexey-sdvizhkov.ru'
