apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: forms-assistant
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - app.alexey-sdvizhkov.ru
      secretName: app-tls
  rules:
    - host: app.alexey-sdvizhkov.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
